# Generated by Django 5.0.3 on 2024-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('dinero', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
    ]
